// Auto-generated by pim-network/scripts/deploy-and-sync.js
// Chain 31337 = Hardhat Local

export const PIM_TOKEN_BY_CHAIN = {
  31337: '0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512',
};

export function pimTokenAddressForChain(chainId) {
  const addr = PIM_TOKEN_BY_CHAIN[chainId];
  if (!addr) return null;
  return addr;
}
